version: "3.7"

services:
  arduino-websocket:
    container_name: arduino-websocket-api
    build:
      context: .
      dockerfile: Dockerfile
    image: arduino-websocket-api
    restart: always
    ports:
      - "172.17.0.1:8080:8080"
      - "127.0.0.1:8080:8080"

