version: "3.7"

services:

  # BACKEND APP
  websocket-api:
    container_name: websocket-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILE: dev
      PORT: 8080
      TZ: America/Sao_Paulo
